//
//  PrivacyMarkersTests.swift
//  ClipyTests
//

import Testing
@testable import Clipy

@Suite struct PrivacyMarkersTests {

    @Test func recordsNormalContent() {
        #expect(PrivacyMarkers.decision(forTypeIdentifiers: ["public.utf8-plain-text"]) == .record)
    }

    @Test func skipsTransient() {
        #expect(PrivacyMarkers.decision(
            forTypeIdentifiers: ["public.utf8-plain-text", PrivacyMarkers.transient]) == .skip)
    }

    @Test func skipsAutoGenerated() {
        #expect(PrivacyMarkers.decision(forTypeIdentifiers: [PrivacyMarkers.autoGenerated]) == .skip)
    }

    @Test func concealedIsConcealed() {
        #expect(PrivacyMarkers.decision(
            forTypeIdentifiers: ["public.utf8-plain-text", PrivacyMarkers.concealed]) == .concealed)
    }

    @Test func legacyTransientMarkersSkip() {
        for marker in PrivacyMarkers.legacyTransient {
            #expect(PrivacyMarkers.decision(forTypeIdentifiers: [marker]) == .skip)
        }
    }

    @Test func legacyConcealedMarkersAreConcealed() {
        for marker in PrivacyMarkers.legacyConcealed {
            #expect(PrivacyMarkers.decision(forTypeIdentifiers: [marker]) == .concealed)
        }
    }

    @Test func skipWinsOverConcealed() {
        #expect(PrivacyMarkers.decision(
            forTypeIdentifiers: [PrivacyMarkers.concealed, PrivacyMarkers.transient]) == .skip)
    }

    @Test func decisionDoesNotDependOnAppIdentifiers() {
        // The decision must be unconditional (not tied to an exclude list) — a frontmost app's
        // bundle id appearing among types must not change a normal "record".
        #expect(PrivacyMarkers.decision(
            forTypeIdentifiers: ["com.apple.TextEdit", "public.utf8-plain-text"]) == .record)
    }
}
