//
//  PrivacyMarkers.swift
//  ClipySi — Apple Silicon rewrite
//
//  Pasteboard privacy markers (R1, security-guidance.md §4). A clipboard manager captures
//  everything a user copies — including passwords/tokens — so before reading ANY content we
//  inspect the pasteboard's declared type identifiers and honor the nspasteboard.org markers:
//
//   - Transient / AutoGenerated (+ legacy synonyms) → never store.
//   - Concealed (+ legacy synonyms)               → don't store by default (opt-in: store
//                                                     encrypted + masked).
//
//  The decision must NOT depend on the user's exclude list — that unconditional gate is the
//  fix for the original's core defect (F1/F2/F9). The pure `decision(forTypeIdentifiers:)` is
//  what capture and tests call; it never touches a live pasteboard.
//

import AppKit

/// What capture should do with a freshly-changed pasteboard, decided from its types alone.
enum CaptureDecision: Sendable, Equatable {
    /// Normal content — capture it.
    case record
    /// Transient / auto-generated — never store.
    case skip
    /// Concealed (e.g. a password field) — skip by default; store only if the user opts in,
    /// and then only through the encrypted path with a masked preview.
    case concealed
}

enum PrivacyMarkers {
    // Canonical org.nspasteboard.* markers.
    static let transient = "org.nspasteboard.TransientType"
    static let concealed = "org.nspasteboard.ConcealedType"
    static let autoGenerated = "org.nspasteboard.AutoGeneratedType"
    /// Source bundle id (informational). We also set this when we write content back, as a
    /// good-citizen behavior.
    static let source = "org.nspasteboard.source"

    /// Legacy synonyms for "transient" predating the org.nspasteboard.* convention.
    static let legacyTransient: Set<String> = [
        "de.petermaurer.TransientPasteboardType", // TextExpander / Butler
        "com.typeit4me.clipping",                 // TypeIt4Me
        "Pasteboard generator type"               // Typinator
    ]
    /// Legacy synonyms for "concealed".
    static let legacyConcealed: Set<String> = [
        "com.agilebits.onepassword"               // 1Password
    ]

    /// Capture decision from pasteboard type identifiers alone. Call BEFORE reading content (R1).
    /// "Skip" wins over "concealed" when both markers are present (safe-side default), because
    /// mis-tagging is common in the wild (security-guidance.md §4).
    static func decision(forTypeIdentifiers identifiers: some Sequence<String>) -> CaptureDecision {
        let types = Set(identifiers)
        if types.contains(transient)
            || types.contains(autoGenerated)
            || !types.isDisjoint(with: legacyTransient) {
            return .skip
        }
        if types.contains(concealed) || !types.isDisjoint(with: legacyConcealed) {
            return .concealed
        }
        return .record
    }
}

extension PrivacyMarkers {
    /// Convenience over a live pasteboard. The markers are written in the same
    /// `clearContents()`/`declareTypes()` transaction as the content, so reading `types`
    /// right after a `changeCount` bump is sufficient.
    @MainActor
    static func decision(for pasteboard: NSPasteboard) -> CaptureDecision {
        decision(forTypeIdentifiers: (pasteboard.types ?? []).map(\.rawValue))
    }
}
