// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(clipy_si_core_ffiFFI)
import clipy_si_core_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_clipy_si_core_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_clipy_si_core_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureClipySiCoreFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt8: FfiConverterPrimitive {
    typealias FfiType = Int8
    typealias SwiftType = Int8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}


/**
 * HLC wire stamp (UUID node as a string).
 */
public struct HlcFfi {
    public var wallMillis: Int64
    public var counter: UInt32
    public var node: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(wallMillis: Int64, counter: UInt32, node: String) {
        self.wallMillis = wallMillis
        self.counter = counter
        self.node = node
    }
}

#if compiler(>=6)
extension HlcFfi: Sendable {}
#endif


extension HlcFfi: Equatable, Hashable {
    public static func ==(lhs: HlcFfi, rhs: HlcFfi) -> Bool {
        if lhs.wallMillis != rhs.wallMillis {
            return false
        }
        if lhs.counter != rhs.counter {
            return false
        }
        if lhs.node != rhs.node {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(wallMillis)
        hasher.combine(counter)
        hasher.combine(node)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHlcFfi: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HlcFfi {
        return
            try HlcFfi(
                wallMillis: FfiConverterInt64.read(from: &buf), 
                counter: FfiConverterUInt32.read(from: &buf), 
                node: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: HlcFfi, into buf: inout [UInt8]) {
        FfiConverterInt64.write(value.wallMillis, into: &buf)
        FfiConverterUInt32.write(value.counter, into: &buf)
        FfiConverterString.write(value.node, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHlcFfi_lift(_ buf: RustBuffer) throws -> HlcFfi {
    return try FfiConverterTypeHlcFfi.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHlcFfi_lower(_ value: HlcFfi) -> RustBuffer {
    return FfiConverterTypeHlcFfi.lower(value)
}


/**
 * KDF descriptor (input only — mirrors `core_lib::KdfDescriptor`).
 */
public struct KdfDescriptorFfi {
    public var kind: KdfKindFfi
    public var salt: Data
    public var kdfVersion: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(kind: KdfKindFfi, salt: Data, kdfVersion: UInt32) {
        self.kind = kind
        self.salt = salt
        self.kdfVersion = kdfVersion
    }
}

#if compiler(>=6)
extension KdfDescriptorFfi: Sendable {}
#endif


extension KdfDescriptorFfi: Equatable, Hashable {
    public static func ==(lhs: KdfDescriptorFfi, rhs: KdfDescriptorFfi) -> Bool {
        if lhs.kind != rhs.kind {
            return false
        }
        if lhs.salt != rhs.salt {
            return false
        }
        if lhs.kdfVersion != rhs.kdfVersion {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(kind)
        hasher.combine(salt)
        hasher.combine(kdfVersion)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeKdfDescriptorFfi: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> KdfDescriptorFfi {
        return
            try KdfDescriptorFfi(
                kind: FfiConverterTypeKdfKindFfi.read(from: &buf), 
                salt: FfiConverterData.read(from: &buf), 
                kdfVersion: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: KdfDescriptorFfi, into buf: inout [UInt8]) {
        FfiConverterTypeKdfKindFfi.write(value.kind, into: &buf)
        FfiConverterData.write(value.salt, into: &buf)
        FfiConverterUInt32.write(value.kdfVersion, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeKdfDescriptorFfi_lift(_ buf: RustBuffer) throws -> KdfDescriptorFfi {
    return try FfiConverterTypeKdfDescriptorFfi.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeKdfDescriptorFfi_lower(_ value: KdfDescriptorFfi) -> RustBuffer {
    return FfiConverterTypeKdfDescriptorFfi.lower(value)
}


/**
 * What the shell knows locally about one incoming record id. Mirrors `core_lib::LocalState`.
 */
public struct LocalStateFfi {
    public var applied: Bool
    public var appliedDeleted: Bool
    public var liveDuplicateSyncHash: Bool
    public var tombstonedDuplicateHlc: HlcFfi?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(applied: Bool, appliedDeleted: Bool, liveDuplicateSyncHash: Bool, tombstonedDuplicateHlc: HlcFfi?) {
        self.applied = applied
        self.appliedDeleted = appliedDeleted
        self.liveDuplicateSyncHash = liveDuplicateSyncHash
        self.tombstonedDuplicateHlc = tombstonedDuplicateHlc
    }
}

#if compiler(>=6)
extension LocalStateFfi: Sendable {}
#endif


extension LocalStateFfi: Equatable, Hashable {
    public static func ==(lhs: LocalStateFfi, rhs: LocalStateFfi) -> Bool {
        if lhs.applied != rhs.applied {
            return false
        }
        if lhs.appliedDeleted != rhs.appliedDeleted {
            return false
        }
        if lhs.liveDuplicateSyncHash != rhs.liveDuplicateSyncHash {
            return false
        }
        if lhs.tombstonedDuplicateHlc != rhs.tombstonedDuplicateHlc {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(applied)
        hasher.combine(appliedDeleted)
        hasher.combine(liveDuplicateSyncHash)
        hasher.combine(tombstonedDuplicateHlc)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLocalStateFfi: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LocalStateFfi {
        return
            try LocalStateFfi(
                applied: FfiConverterBool.read(from: &buf), 
                appliedDeleted: FfiConverterBool.read(from: &buf), 
                liveDuplicateSyncHash: FfiConverterBool.read(from: &buf), 
                tombstonedDuplicateHlc: FfiConverterOptionTypeHlcFfi.read(from: &buf)
        )
    }

    public static func write(_ value: LocalStateFfi, into buf: inout [UInt8]) {
        FfiConverterBool.write(value.applied, into: &buf)
        FfiConverterBool.write(value.appliedDeleted, into: &buf)
        FfiConverterBool.write(value.liveDuplicateSyncHash, into: &buf)
        FfiConverterOptionTypeHlcFfi.write(value.tombstonedDuplicateHlc, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLocalStateFfi_lift(_ buf: RustBuffer) throws -> LocalStateFfi {
    return try FfiConverterTypeLocalStateFfi.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLocalStateFfi_lower(_ value: LocalStateFfi) -> RustBuffer {
    return FfiConverterTypeLocalStateFfi.lower(value)
}


/**
 * Detection + masking configuration. Mirrors `core_lib::MaskConfig`.
 */
public struct MaskConfig {
    public var enabled: Bool
    public var style: MaskStyle
    public var minEntropyLen: UInt32
    public var entropyBits: Double
    public var userRules: [UserRule]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(enabled: Bool, style: MaskStyle, minEntropyLen: UInt32, entropyBits: Double, userRules: [UserRule]) {
        self.enabled = enabled
        self.style = style
        self.minEntropyLen = minEntropyLen
        self.entropyBits = entropyBits
        self.userRules = userRules
    }
}

#if compiler(>=6)
extension MaskConfig: Sendable {}
#endif


extension MaskConfig: Equatable, Hashable {
    public static func ==(lhs: MaskConfig, rhs: MaskConfig) -> Bool {
        if lhs.enabled != rhs.enabled {
            return false
        }
        if lhs.style != rhs.style {
            return false
        }
        if lhs.minEntropyLen != rhs.minEntropyLen {
            return false
        }
        if lhs.entropyBits != rhs.entropyBits {
            return false
        }
        if lhs.userRules != rhs.userRules {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(enabled)
        hasher.combine(style)
        hasher.combine(minEntropyLen)
        hasher.combine(entropyBits)
        hasher.combine(userRules)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMaskConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MaskConfig {
        return
            try MaskConfig(
                enabled: FfiConverterBool.read(from: &buf), 
                style: FfiConverterTypeMaskStyle.read(from: &buf), 
                minEntropyLen: FfiConverterUInt32.read(from: &buf), 
                entropyBits: FfiConverterDouble.read(from: &buf), 
                userRules: FfiConverterSequenceTypeUserRule.read(from: &buf)
        )
    }

    public static func write(_ value: MaskConfig, into buf: inout [UInt8]) {
        FfiConverterBool.write(value.enabled, into: &buf)
        FfiConverterTypeMaskStyle.write(value.style, into: &buf)
        FfiConverterUInt32.write(value.minEntropyLen, into: &buf)
        FfiConverterDouble.write(value.entropyBits, into: &buf)
        FfiConverterSequenceTypeUserRule.write(value.userRules, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMaskConfig_lift(_ buf: RustBuffer) throws -> MaskConfig {
    return try FfiConverterTypeMaskConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMaskConfig_lower(_ value: MaskConfig) -> RustBuffer {
    return FfiConverterTypeMaskConfig.lower(value)
}


/**
 * One-pass verdict + display. Mirrors `core_lib::MaskEvaluation` (M-UI.11 P1-R).
 */
public struct MaskEvaluation {
    /**
     * A secret was detected (like `is_secret`, independent of `config.enabled`).
     */
    public var isSecret: Bool
    /**
     * What to render (identical to `mask` for the same text/config).
     */
    public var display: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * A secret was detected (like `is_secret`, independent of `config.enabled`).
         */isSecret: Bool, 
        /**
         * What to render (identical to `mask` for the same text/config).
         */display: String) {
        self.isSecret = isSecret
        self.display = display
    }
}

#if compiler(>=6)
extension MaskEvaluation: Sendable {}
#endif


extension MaskEvaluation: Equatable, Hashable {
    public static func ==(lhs: MaskEvaluation, rhs: MaskEvaluation) -> Bool {
        if lhs.isSecret != rhs.isSecret {
            return false
        }
        if lhs.display != rhs.display {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(isSecret)
        hasher.combine(display)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMaskEvaluation: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MaskEvaluation {
        return
            try MaskEvaluation(
                isSecret: FfiConverterBool.read(from: &buf), 
                display: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: MaskEvaluation, into buf: inout [UInt8]) {
        FfiConverterBool.write(value.isSecret, into: &buf)
        FfiConverterString.write(value.display, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMaskEvaluation_lift(_ buf: RustBuffer) throws -> MaskEvaluation {
    return try FfiConverterTypeMaskEvaluation.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMaskEvaluation_lower(_ value: MaskEvaluation) -> RustBuffer {
    return FfiConverterTypeMaskEvaluation.lower(value)
}


/**
 * A full record envelope (header + optional sealed body). `body == None` is a tombstone.
 */
public struct RecordEnvelopeFfi {
    public var header: RecordHeaderFfi
    public var body: Data?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(header: RecordHeaderFfi, body: Data?) {
        self.header = header
        self.body = body
    }
}

#if compiler(>=6)
extension RecordEnvelopeFfi: Sendable {}
#endif


extension RecordEnvelopeFfi: Equatable, Hashable {
    public static func ==(lhs: RecordEnvelopeFfi, rhs: RecordEnvelopeFfi) -> Bool {
        if lhs.header != rhs.header {
            return false
        }
        if lhs.body != rhs.body {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(header)
        hasher.combine(body)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRecordEnvelopeFfi: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RecordEnvelopeFfi {
        return
            try RecordEnvelopeFfi(
                header: FfiConverterTypeRecordHeaderFfi.read(from: &buf), 
                body: FfiConverterOptionData.read(from: &buf)
        )
    }

    public static func write(_ value: RecordEnvelopeFfi, into buf: inout [UInt8]) {
        FfiConverterTypeRecordHeaderFfi.write(value.header, into: &buf)
        FfiConverterOptionData.write(value.body, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRecordEnvelopeFfi_lift(_ buf: RustBuffer) throws -> RecordEnvelopeFfi {
    return try FfiConverterTypeRecordEnvelopeFfi.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRecordEnvelopeFfi_lower(_ value: RecordEnvelopeFfi) -> RustBuffer {
    return FfiConverterTypeRecordEnvelopeFfi.lower(value)
}


/**
 * Plaintext routing/merge header (UUIDs as strings).
 */
public struct RecordHeaderFfi {
    public var formatVersion: UInt32
    public var recordId: String
    public var originDeviceId: String
    public var hlc: HlcFfi
    public var createdAt: Int64
    public var updatedAt: Int64
    public var deleted: Bool
    public var syncHash: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(formatVersion: UInt32, recordId: String, originDeviceId: String, hlc: HlcFfi, createdAt: Int64, updatedAt: Int64, deleted: Bool, syncHash: String) {
        self.formatVersion = formatVersion
        self.recordId = recordId
        self.originDeviceId = originDeviceId
        self.hlc = hlc
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.deleted = deleted
        self.syncHash = syncHash
    }
}

#if compiler(>=6)
extension RecordHeaderFfi: Sendable {}
#endif


extension RecordHeaderFfi: Equatable, Hashable {
    public static func ==(lhs: RecordHeaderFfi, rhs: RecordHeaderFfi) -> Bool {
        if lhs.formatVersion != rhs.formatVersion {
            return false
        }
        if lhs.recordId != rhs.recordId {
            return false
        }
        if lhs.originDeviceId != rhs.originDeviceId {
            return false
        }
        if lhs.hlc != rhs.hlc {
            return false
        }
        if lhs.createdAt != rhs.createdAt {
            return false
        }
        if lhs.updatedAt != rhs.updatedAt {
            return false
        }
        if lhs.deleted != rhs.deleted {
            return false
        }
        if lhs.syncHash != rhs.syncHash {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(formatVersion)
        hasher.combine(recordId)
        hasher.combine(originDeviceId)
        hasher.combine(hlc)
        hasher.combine(createdAt)
        hasher.combine(updatedAt)
        hasher.combine(deleted)
        hasher.combine(syncHash)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRecordHeaderFfi: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RecordHeaderFfi {
        return
            try RecordHeaderFfi(
                formatVersion: FfiConverterUInt32.read(from: &buf), 
                recordId: FfiConverterString.read(from: &buf), 
                originDeviceId: FfiConverterString.read(from: &buf), 
                hlc: FfiConverterTypeHlcFfi.read(from: &buf), 
                createdAt: FfiConverterInt64.read(from: &buf), 
                updatedAt: FfiConverterInt64.read(from: &buf), 
                deleted: FfiConverterBool.read(from: &buf), 
                syncHash: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: RecordHeaderFfi, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.formatVersion, into: &buf)
        FfiConverterString.write(value.recordId, into: &buf)
        FfiConverterString.write(value.originDeviceId, into: &buf)
        FfiConverterTypeHlcFfi.write(value.hlc, into: &buf)
        FfiConverterInt64.write(value.createdAt, into: &buf)
        FfiConverterInt64.write(value.updatedAt, into: &buf)
        FfiConverterBool.write(value.deleted, into: &buf)
        FfiConverterString.write(value.syncHash, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRecordHeaderFfi_lift(_ buf: RustBuffer) throws -> RecordHeaderFfi {
    return try FfiConverterTypeRecordHeaderFfi.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRecordHeaderFfi_lower(_ value: RecordHeaderFfi) -> RustBuffer {
    return FfiConverterTypeRecordHeaderFfi.lower(value)
}


/**
 * The plaintext content of a record (what `seal_record` encrypts).
 */
public struct RecordPlaintextFfi {
    public var title: String
    public var primaryType: String
    public var sourceBundle: String?
    public var isColorCode: Bool
    public var representations: [RecordRepresentationFfi]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(title: String, primaryType: String, sourceBundle: String?, isColorCode: Bool, representations: [RecordRepresentationFfi]) {
        self.title = title
        self.primaryType = primaryType
        self.sourceBundle = sourceBundle
        self.isColorCode = isColorCode
        self.representations = representations
    }
}

#if compiler(>=6)
extension RecordPlaintextFfi: Sendable {}
#endif


extension RecordPlaintextFfi: Equatable, Hashable {
    public static func ==(lhs: RecordPlaintextFfi, rhs: RecordPlaintextFfi) -> Bool {
        if lhs.title != rhs.title {
            return false
        }
        if lhs.primaryType != rhs.primaryType {
            return false
        }
        if lhs.sourceBundle != rhs.sourceBundle {
            return false
        }
        if lhs.isColorCode != rhs.isColorCode {
            return false
        }
        if lhs.representations != rhs.representations {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(title)
        hasher.combine(primaryType)
        hasher.combine(sourceBundle)
        hasher.combine(isColorCode)
        hasher.combine(representations)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRecordPlaintextFfi: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RecordPlaintextFfi {
        return
            try RecordPlaintextFfi(
                title: FfiConverterString.read(from: &buf), 
                primaryType: FfiConverterString.read(from: &buf), 
                sourceBundle: FfiConverterOptionString.read(from: &buf), 
                isColorCode: FfiConverterBool.read(from: &buf), 
                representations: FfiConverterSequenceTypeRecordRepresentationFfi.read(from: &buf)
        )
    }

    public static func write(_ value: RecordPlaintextFfi, into buf: inout [UInt8]) {
        FfiConverterString.write(value.title, into: &buf)
        FfiConverterString.write(value.primaryType, into: &buf)
        FfiConverterOptionString.write(value.sourceBundle, into: &buf)
        FfiConverterBool.write(value.isColorCode, into: &buf)
        FfiConverterSequenceTypeRecordRepresentationFfi.write(value.representations, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRecordPlaintextFfi_lift(_ buf: RustBuffer) throws -> RecordPlaintextFfi {
    return try FfiConverterTypeRecordPlaintextFfi.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRecordPlaintextFfi_lower(_ value: RecordPlaintextFfi) -> RustBuffer {
    return FfiConverterTypeRecordPlaintextFfi.lower(value)
}


/**
 * One captured representation (uttype + bytes).
 */
public struct RecordRepresentationFfi {
    public var uttype: String
    public var data: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(uttype: String, data: Data) {
        self.uttype = uttype
        self.data = data
    }
}

#if compiler(>=6)
extension RecordRepresentationFfi: Sendable {}
#endif


extension RecordRepresentationFfi: Equatable, Hashable {
    public static func ==(lhs: RecordRepresentationFfi, rhs: RecordRepresentationFfi) -> Bool {
        if lhs.uttype != rhs.uttype {
            return false
        }
        if lhs.data != rhs.data {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(uttype)
        hasher.combine(data)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRecordRepresentationFfi: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RecordRepresentationFfi {
        return
            try RecordRepresentationFfi(
                uttype: FfiConverterString.read(from: &buf), 
                data: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: RecordRepresentationFfi, into buf: inout [UInt8]) {
        FfiConverterString.write(value.uttype, into: &buf)
        FfiConverterData.write(value.data, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRecordRepresentationFfi_lift(_ buf: RustBuffer) throws -> RecordRepresentationFfi {
    return try FfiConverterTypeRecordRepresentationFfi.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRecordRepresentationFfi_lower(_ value: RecordRepresentationFfi) -> RustBuffer {
    return FfiConverterTypeRecordRepresentationFfi.lower(value)
}


/**
 * A detected secret span. `kind` is the stable `SecretKind::as_str()` label.
 */
public struct SecretMatch {
    public var kind: String
    public var start: UInt32
    public var end: UInt32
    public var confidence: Confidence

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(kind: String, start: UInt32, end: UInt32, confidence: Confidence) {
        self.kind = kind
        self.start = start
        self.end = end
        self.confidence = confidence
    }
}

#if compiler(>=6)
extension SecretMatch: Sendable {}
#endif


extension SecretMatch: Equatable, Hashable {
    public static func ==(lhs: SecretMatch, rhs: SecretMatch) -> Bool {
        if lhs.kind != rhs.kind {
            return false
        }
        if lhs.start != rhs.start {
            return false
        }
        if lhs.end != rhs.end {
            return false
        }
        if lhs.confidence != rhs.confidence {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(kind)
        hasher.combine(start)
        hasher.combine(end)
        hasher.combine(confidence)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSecretMatch: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SecretMatch {
        return
            try SecretMatch(
                kind: FfiConverterString.read(from: &buf), 
                start: FfiConverterUInt32.read(from: &buf), 
                end: FfiConverterUInt32.read(from: &buf), 
                confidence: FfiConverterTypeConfidence.read(from: &buf)
        )
    }

    public static func write(_ value: SecretMatch, into buf: inout [UInt8]) {
        FfiConverterString.write(value.kind, into: &buf)
        FfiConverterUInt32.write(value.start, into: &buf)
        FfiConverterUInt32.write(value.end, into: &buf)
        FfiConverterTypeConfidence.write(value.confidence, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSecretMatch_lift(_ buf: RustBuffer) throws -> SecretMatch {
    return try FfiConverterTypeSecretMatch.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSecretMatch_lower(_ value: SecretMatch) -> RustBuffer {
    return FfiConverterTypeSecretMatch.lower(value)
}


/**
 * A user-supplied detection rule. Mirrors `core_lib::UserRule`.
 */
public struct UserRule {
    public var name: String
    public var regex: String
    public var kindLabel: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, regex: String, kindLabel: String) {
        self.name = name
        self.regex = regex
        self.kindLabel = kindLabel
    }
}

#if compiler(>=6)
extension UserRule: Sendable {}
#endif


extension UserRule: Equatable, Hashable {
    public static func ==(lhs: UserRule, rhs: UserRule) -> Bool {
        if lhs.name != rhs.name {
            return false
        }
        if lhs.regex != rhs.regex {
            return false
        }
        if lhs.kindLabel != rhs.kindLabel {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(name)
        hasher.combine(regex)
        hasher.combine(kindLabel)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeUserRule: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UserRule {
        return
            try UserRule(
                name: FfiConverterString.read(from: &buf), 
                regex: FfiConverterString.read(from: &buf), 
                kindLabel: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: UserRule, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.regex, into: &buf)
        FfiConverterString.write(value.kindLabel, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUserRule_lift(_ buf: RustBuffer) throws -> UserRule {
    return try FfiConverterTypeUserRule.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUserRule_lower(_ value: UserRule) -> RustBuffer {
    return FfiConverterTypeUserRule.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Detector confidence. Mirrors `core_lib::Confidence`.
 */

public enum Confidence {
    
    /**
     * A definite literal pattern.
     */
    case high
    /**
     * An entropy heuristic.
     */
    case medium
}


#if compiler(>=6)
extension Confidence: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeConfidence: FfiConverterRustBuffer {
    typealias SwiftType = Confidence

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Confidence {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .high
        
        case 2: return .medium
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Confidence, into buf: inout [UInt8]) {
        switch value {
        
        
        case .high:
            writeInt(&buf, Int32(1))
        
        
        case .medium:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConfidence_lift(_ buf: RustBuffer) throws -> Confidence {
    return try FfiConverterTypeConfidence.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConfidence_lower(_ value: Confidence) -> RustBuffer {
    return FfiConverterTypeConfidence.lower(value)
}


extension Confidence: Equatable, Hashable {}







/**
 * Fallible-operation error (crypto/KDF/format). Mirrors `core_lib::CoreError`; value-free.
 */
public enum CoreErrorFfi: Swift.Error {

    
    
    case InvalidInput
    case DecryptFailed
    case UnsupportedFormat
    case KdfFailed
    /**
     * A core error category added after this binding was built (forward-compat catch-all).
     */
    case Unknown
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCoreErrorFfi: FfiConverterRustBuffer {
    typealias SwiftType = CoreErrorFfi

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CoreErrorFfi {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .InvalidInput
        case 2: return .DecryptFailed
        case 3: return .UnsupportedFormat
        case 4: return .KdfFailed
        case 5: return .Unknown

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CoreErrorFfi, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case .InvalidInput:
            writeInt(&buf, Int32(1))
        
        
        case .DecryptFailed:
            writeInt(&buf, Int32(2))
        
        
        case .UnsupportedFormat:
            writeInt(&buf, Int32(3))
        
        
        case .KdfFailed:
            writeInt(&buf, Int32(4))
        
        
        case .Unknown:
            writeInt(&buf, Int32(5))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCoreErrorFfi_lift(_ buf: RustBuffer) throws -> CoreErrorFfi {
    return try FfiConverterTypeCoreErrorFfi.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCoreErrorFfi_lower(_ value: CoreErrorFfi) -> RustBuffer {
    return FfiConverterTypeCoreErrorFfi.lower(value)
}


extension CoreErrorFfi: Equatable, Hashable {}




extension CoreErrorFfi: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}




// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * KDF algorithm (input only — mirrors `core_lib::KdfKind`).
 */

public enum KdfKindFfi {
    
    case pbkdf2HmacSha256(iterations: UInt32
    )
}


#if compiler(>=6)
extension KdfKindFfi: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeKdfKindFfi: FfiConverterRustBuffer {
    typealias SwiftType = KdfKindFfi

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> KdfKindFfi {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .pbkdf2HmacSha256(iterations: try FfiConverterUInt32.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: KdfKindFfi, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .pbkdf2HmacSha256(iterations):
            writeInt(&buf, Int32(1))
            FfiConverterUInt32.write(iterations, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeKdfKindFfi_lift(_ buf: RustBuffer) throws -> KdfKindFfi {
    return try FfiConverterTypeKdfKindFfi.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeKdfKindFfi_lower(_ value: KdfKindFfi) -> RustBuffer {
    return FfiConverterTypeKdfKindFfi.lower(value)
}


extension KdfKindFfi: Equatable, Hashable {}






// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * How a detected-secret string is rendered for display. Mirrors `core_lib::MaskStyle`.
 */

public enum MaskStyle {
    
    /**
     * Replace every character with a bullet (hides the whole value). Default.
     */
    case full
    /**
     * Keep the first two characters, mask the rest.
     */
    case prefix2
    /**
     * Keep the last four characters, mask the rest.
     */
    case suffix4
}


#if compiler(>=6)
extension MaskStyle: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMaskStyle: FfiConverterRustBuffer {
    typealias SwiftType = MaskStyle

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MaskStyle {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .full
        
        case 2: return .prefix2
        
        case 3: return .suffix4
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: MaskStyle, into buf: inout [UInt8]) {
        switch value {
        
        
        case .full:
            writeInt(&buf, Int32(1))
        
        
        case .prefix2:
            writeInt(&buf, Int32(2))
        
        
        case .suffix4:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMaskStyle_lift(_ buf: RustBuffer) throws -> MaskStyle {
    return try FfiConverterTypeMaskStyle.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMaskStyle_lower(_ value: MaskStyle) -> RustBuffer {
    return FfiConverterTypeMaskStyle.lower(value)
}


extension MaskStyle: Equatable, Hashable {}






// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Merge decision for one incoming envelope. Mirrors `core_lib::MergeAction`.
 */

public enum MergeActionFfi {
    
    case applyRemote
    case applyTombstone
    case recordTombstoneOnly
    case skip
    case skipDuplicateContent
}


#if compiler(>=6)
extension MergeActionFfi: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMergeActionFfi: FfiConverterRustBuffer {
    typealias SwiftType = MergeActionFfi

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MergeActionFfi {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .applyRemote
        
        case 2: return .applyTombstone
        
        case 3: return .recordTombstoneOnly
        
        case 4: return .skip
        
        case 5: return .skipDuplicateContent
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: MergeActionFfi, into buf: inout [UInt8]) {
        switch value {
        
        
        case .applyRemote:
            writeInt(&buf, Int32(1))
        
        
        case .applyTombstone:
            writeInt(&buf, Int32(2))
        
        
        case .recordTombstoneOnly:
            writeInt(&buf, Int32(3))
        
        
        case .skip:
            writeInt(&buf, Int32(4))
        
        
        case .skipDuplicateContent:
            writeInt(&buf, Int32(5))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMergeActionFfi_lift(_ buf: RustBuffer) throws -> MergeActionFfi {
    return try FfiConverterTypeMergeActionFfi.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMergeActionFfi_lower(_ value: MergeActionFfi) -> RustBuffer {
    return FfiConverterTypeMergeActionFfi.lower(value)
}


extension MergeActionFfi: Equatable, Hashable {}






// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Stale-rejoin decision. Mirrors `core_lib::RejoinAction`.
 */

public enum RejoinActionFfi {
    
    case deleteLocally
    case repush
}


#if compiler(>=6)
extension RejoinActionFfi: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRejoinActionFfi: FfiConverterRustBuffer {
    typealias SwiftType = RejoinActionFfi

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RejoinActionFfi {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .deleteLocally
        
        case 2: return .repush
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: RejoinActionFfi, into buf: inout [UInt8]) {
        switch value {
        
        
        case .deleteLocally:
            writeInt(&buf, Int32(1))
        
        
        case .repush:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRejoinActionFfi_lift(_ buf: RustBuffer) throws -> RejoinActionFfi {
    return try FfiConverterTypeRejoinActionFfi.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRejoinActionFfi_lower(_ value: RejoinActionFfi) -> RustBuffer {
    return FfiConverterTypeRejoinActionFfi.lower(value)
}


extension RejoinActionFfi: Equatable, Hashable {}






#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionData: FfiConverterRustBuffer {
    typealias SwiftType = Data?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterData.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterData.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeHlcFfi: FfiConverterRustBuffer {
    typealias SwiftType = HlcFfi?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeHlcFfi.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeHlcFfi.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceInt64: FfiConverterRustBuffer {
    typealias SwiftType = [Int64]

    public static func write(_ value: [Int64], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterInt64.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Int64] {
        let len: Int32 = try readInt(&buf)
        var seq = [Int64]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterInt64.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeRecordRepresentationFfi: FfiConverterRustBuffer {
    typealias SwiftType = [RecordRepresentationFfi]

    public static func write(_ value: [RecordRepresentationFfi], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeRecordRepresentationFfi.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [RecordRepresentationFfi] {
        let len: Int32 = try readInt(&buf)
        var seq = [RecordRepresentationFfi]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeRecordRepresentationFfi.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeSecretMatch: FfiConverterRustBuffer {
    typealias SwiftType = [SecretMatch]

    public static func write(_ value: [SecretMatch], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSecretMatch.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [SecretMatch] {
        let len: Int32 = try readInt(&buf)
        var seq = [SecretMatch]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeSecretMatch.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeUserRule: FfiConverterRustBuffer {
    typealias SwiftType = [UserRule]

    public static func write(_ value: [UserRule], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeUserRule.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [UserRule] {
        let len: Int32 = try readInt(&buf)
        var seq = [UserRule]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeUserRule.read(from: &buf))
        }
        return seq
    }
}
/**
 * Cross-device dedupe hash over the canonical payload (vault dedupe subkey).
 */
public func computeSyncHash(vaultKey: Data, canonicalPayload: Data)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCoreErrorFfi_lift) {
    uniffi_clipy_si_core_ffi_fn_func_compute_sync_hash(
        FfiConverterData.lower(vaultKey),
        FfiConverterData.lower(canonicalPayload),$0
    )
})
}
/**
 * Keyed dedupe hash (HMAC-SHA256, lowercase hex) — CryptoKit-compatible.
 */
public func contentHash(key: Data, payload: Data) -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_clipy_si_core_ffi_fn_func_content_hash(
        FfiConverterData.lower(key),
        FfiConverterData.lower(payload),$0
    )
})
}
/**
 * Decode `.cclip` wire bytes into an envelope (rejects unknown version / invalid tombstone).
 */
public func decodeEnvelope(bytes: Data)throws  -> RecordEnvelopeFfi  {
    return try  FfiConverterTypeRecordEnvelopeFfi_lift(try rustCallWithError(FfiConverterTypeCoreErrorFfi_lift) {
    uniffi_clipy_si_core_ffi_fn_func_decode_envelope(
        FfiConverterData.lower(bytes),$0
    )
})
}
/**
 * The default configuration: masking **ON**, style **Full**.
 */
public func defaultConfig() -> MaskConfig  {
    return try!  FfiConverterTypeMaskConfig_lift(try! rustCall() {
    uniffi_clipy_si_core_ffi_fn_func_default_config($0
    )
})
}
/**
 * Derive the 32-byte vault key from a passphrase (NFC-normalised PBKDF2).
 */
public func deriveVaultKey(passphrase: String, kdf: KdfDescriptorFfi)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeCoreErrorFfi_lift) {
    uniffi_clipy_si_core_ffi_fn_func_derive_vault_key(
        FfiConverterString.lower(passphrase),
        FfiConverterTypeKdfDescriptorFfi_lower(kdf),$0
    )
})
}
/**
 * Enumerate the secret spans in `text` (char offsets). Ignores `config.enabled`.
 */
public func detectSecrets(text: String, config: MaskConfig) -> [SecretMatch]  {
    return try!  FfiConverterSequenceTypeSecretMatch.lift(try! rustCall() {
    uniffi_clipy_si_core_ffi_fn_func_detect_secrets(
        FfiConverterString.lower(text),
        FfiConverterTypeMaskConfig_lower(config),$0
    )
})
}
/**
 * Whether a device is stale (no longer blocks GC; must run stale-rejoin when it returns).
 */
public func deviceIsStale(lastSeenSecs: Int64, nowSecs: Int64) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_clipy_si_core_ffi_fn_func_device_is_stale(
        FfiConverterInt64.lower(lastSeenSecs),
        FfiConverterInt64.lower(nowSecs),$0
    )
})
}
/**
 * Encode an envelope to its `.cclip` wire bytes (enforces the tombstone invariant).
 */
public func encodeEnvelope(envelope: RecordEnvelopeFfi)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeCoreErrorFfi_lift) {
    uniffi_clipy_si_core_ffi_fn_func_encode_envelope(
        FfiConverterTypeRecordEnvelopeFfi_lower(envelope),$0
    )
})
}
/**
 * Evaluate `text` once: the detector runs a single time and both `is_secret` and `display`
 * come from that one result — equivalent to calling `is_secret` then `mask`, at half the cost.
 */
public func evaluate(text: String, config: MaskConfig) -> MaskEvaluation  {
    return try!  FfiConverterTypeMaskEvaluation_lift(try! rustCall() {
    uniffi_clipy_si_core_ffi_fn_func_evaluate(
        FfiConverterString.lower(text),
        FfiConverterTypeMaskConfig_lower(config),$0
    )
})
}
/**
 * May this tombstone file be removed from the provider? (`last_seen` values are unix SECONDS.)
 */
public func gcEligible(tombstoneHlc: HlcFfi, devicesLastSeenSecs: [Int64], nowSecs: Int64)throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeCoreErrorFfi_lift) {
    uniffi_clipy_si_core_ffi_fn_func_gc_eligible(
        FfiConverterTypeHlcFfi_lower(tombstoneHlc),
        FfiConverterSequenceInt64.lower(devicesLastSeenSecs),
        FfiConverterInt64.lower(nowSecs),$0
    )
})
}
/**
 * Total order over HLC stamps: -1 (a < b), 0 (equal), 1 (a > b).
 */
public func hlcCompare(a: HlcFfi, b: HlcFfi)throws  -> Int8  {
    return try  FfiConverterInt8.lift(try rustCallWithError(FfiConverterTypeCoreErrorFfi_lift) {
    uniffi_clipy_si_core_ffi_fn_func_hlc_compare(
        FfiConverterTypeHlcFfi_lower(a),
        FfiConverterTypeHlcFfi_lower(b),$0
    )
})
}
/**
 * Next HLC stamp this device issues before publishing. `node` is this device's UUID string.
 */
public func hlcNext(prev: HlcFfi?, nowMillis: Int64, node: String)throws  -> HlcFfi  {
    return try  FfiConverterTypeHlcFfi_lift(try rustCallWithError(FfiConverterTypeCoreErrorFfi_lift) {
    uniffi_clipy_si_core_ffi_fn_func_hlc_next(
        FfiConverterOptionTypeHlcFfi.lower(prev),
        FfiConverterInt64.lower(nowMillis),
        FfiConverterString.lower(node),$0
    )
})
}
/**
 * Merge a received stamp into the local clock (skew-clamped; header stamps are never rewritten).
 */
public func hlcReceive(local: HlcFfi?, remote: HlcFfi, nowMillis: Int64, node: String)throws  -> HlcFfi  {
    return try  FfiConverterTypeHlcFfi_lift(try rustCallWithError(FfiConverterTypeCoreErrorFfi_lift) {
    uniffi_clipy_si_core_ffi_fn_func_hlc_receive(
        FfiConverterOptionTypeHlcFfi.lower(local),
        FfiConverterTypeHlcFfi_lower(remote),
        FfiConverterInt64.lower(nowMillis),
        FfiConverterString.lower(node),$0
    )
})
}
/**
 * Fast yes/no used by the UI to mark a row masked. Ignores `config.enabled`.
 */
public func isSecret(text: String, config: MaskConfig) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_clipy_si_core_ffi_fn_func_is_secret(
        FfiConverterString.lower(text),
        FfiConverterTypeMaskConfig_lower(config),$0
    )
})
}
/**
 * AES-256-GCM open of a `.combined` box.
 */
public func localOpen(key: Data, combined: Data)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeCoreErrorFfi_lift) {
    uniffi_clipy_si_core_ffi_fn_func_local_open(
        FfiConverterData.lower(key),
        FfiConverterData.lower(combined),$0
    )
})
}
/**
 * AES-256-GCM seal (CryptoKit `.combined` compatible). `nonce` is 12 caller-supplied CSPRNG bytes.
 */
public func localSeal(key: Data, nonce: Data, plaintext: Data)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeCoreErrorFfi_lift) {
    uniffi_clipy_si_core_ffi_fn_func_local_seal(
        FfiConverterData.lower(key),
        FfiConverterData.lower(nonce),
        FfiConverterData.lower(plaintext),$0
    )
})
}
/**
 * Build `vault.json` bytes, sealing the verifier under the cclip subkey. (No key/passphrase in it.)
 */
public func makeVaultManifest(vaultKey: Data, vaultId: String, createdAt: Int64, kdf: KdfDescriptorFfi, verifierNonce: Data)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeCoreErrorFfi_lift) {
    uniffi_clipy_si_core_ffi_fn_func_make_vault_manifest(
        FfiConverterData.lower(vaultKey),
        FfiConverterString.lower(vaultId),
        FfiConverterInt64.lower(createdAt),
        FfiConverterTypeKdfDescriptorFfi_lower(kdf),
        FfiConverterData.lower(verifierNonce),$0
    )
})
}
/**
 * Extract the KDF descriptor from `vault.json` bytes so the shell can derive the right key for
 * an existing vault (M10 hand-off). Unknown KDF kind / version → `unsupportedFormat`.
 */
public func manifestKdf(manifestJson: Data)throws  -> KdfDescriptorFfi  {
    return try  FfiConverterTypeKdfDescriptorFfi_lift(try rustCallWithError(FfiConverterTypeCoreErrorFfi_lift) {
    uniffi_clipy_si_core_ffi_fn_func_manifest_kdf(
        FfiConverterData.lower(manifestJson),$0
    )
})
}
/**
 * Apply `config.style` and return the display string (original text when `enabled=false`
 * or nothing is detected).
 */
public func mask(text: String, config: MaskConfig) -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_clipy_si_core_ffi_fn_func_mask(
        FfiConverterString.lower(text),
        FfiConverterTypeMaskConfig_lower(config),$0
    )
})
}
/**
 * Decide what to do with one incoming envelope (pull must process tombstones first).
 */
public func mergeDecide(local: LocalStateFfi, remoteDeleted: Bool, remoteHlc: HlcFfi)throws  -> MergeActionFfi  {
    return try  FfiConverterTypeMergeActionFfi_lift(try rustCallWithError(FfiConverterTypeCoreErrorFfi_lift) {
    uniffi_clipy_si_core_ffi_fn_func_merge_decide(
        FfiConverterTypeLocalStateFfi_lower(local),
        FfiConverterBool.lower(remoteDeleted),
        FfiConverterTypeHlcFfi_lower(remoteHlc),$0
    )
})
}
/**
 * Open a sealed body back into a plaintext.
 */
public func openRecord(vaultKey: Data, body: Data)throws  -> RecordPlaintextFfi  {
    return try  FfiConverterTypeRecordPlaintextFfi_lift(try rustCallWithError(FfiConverterTypeCoreErrorFfi_lift) {
    uniffi_clipy_si_core_ffi_fn_func_open_record(
        FfiConverterData.lower(vaultKey),
        FfiConverterData.lower(body),$0
    )
})
}
/**
 * The frozen record wire version.
 */
public func recordFormatVersion() -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_clipy_si_core_ffi_fn_func_record_format_version($0
    )
})
}
/**
 * Rejoin behaviour for previously-published records now absent from records/ AND tombs/.
 */
public func rejoinAction(selfLastSeenSecs: Int64, nowSecs: Int64) -> RejoinActionFfi  {
    return try!  FfiConverterTypeRejoinActionFfi_lift(try! rustCall() {
    uniffi_clipy_si_core_ffi_fn_func_rejoin_action(
        FfiConverterInt64.lower(selfLastSeenSecs),
        FfiConverterInt64.lower(nowSecs),$0
    )
})
}
/**
 * The detection ruleset version (KAT / cross-binding compatibility pin).
 */
public func rulesVersion() -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_clipy_si_core_ffi_fn_func_rules_version($0
    )
})
}
/**
 * Seal a plaintext body under the vault cclip subkey; returns the `.combined` body bytes.
 */
public func sealRecord(vaultKey: Data, nonce: Data, plaintext: RecordPlaintextFfi)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeCoreErrorFfi_lift) {
    uniffi_clipy_si_core_ffi_fn_func_seal_record(
        FfiConverterData.lower(vaultKey),
        FfiConverterData.lower(nonce),
        FfiConverterTypeRecordPlaintextFfi_lower(plaintext),$0
    )
})
}
/**
 * Names of user rules whose regex failed to compile (non-fatal; never carries a value).
 */
public func userRuleErrors(config: MaskConfig) -> [String]  {
    return try!  FfiConverterSequenceString.lift(try! rustCall() {
    uniffi_clipy_si_core_ffi_fn_func_user_rule_errors(
        FfiConverterTypeMaskConfig_lower(config),$0
    )
})
}
/**
 * True iff `vault_key` opens the verifier in the given `vault.json` bytes (right passphrase).
 */
public func verifyPassphrase(vaultKey: Data, manifestJson: Data)throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeCoreErrorFfi_lift) {
    uniffi_clipy_si_core_ffi_fn_func_verify_passphrase(
        FfiConverterData.lower(vaultKey),
        FfiConverterData.lower(manifestJson),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_clipy_si_core_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_clipy_si_core_ffi_checksum_func_compute_sync_hash() != 3117) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clipy_si_core_ffi_checksum_func_content_hash() != 399) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clipy_si_core_ffi_checksum_func_decode_envelope() != 36545) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clipy_si_core_ffi_checksum_func_default_config() != 56306) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clipy_si_core_ffi_checksum_func_derive_vault_key() != 47983) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clipy_si_core_ffi_checksum_func_detect_secrets() != 62307) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clipy_si_core_ffi_checksum_func_device_is_stale() != 58168) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clipy_si_core_ffi_checksum_func_encode_envelope() != 53837) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clipy_si_core_ffi_checksum_func_evaluate() != 61827) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clipy_si_core_ffi_checksum_func_gc_eligible() != 38605) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clipy_si_core_ffi_checksum_func_hlc_compare() != 17506) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clipy_si_core_ffi_checksum_func_hlc_next() != 19537) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clipy_si_core_ffi_checksum_func_hlc_receive() != 6879) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clipy_si_core_ffi_checksum_func_is_secret() != 32589) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clipy_si_core_ffi_checksum_func_local_open() != 47534) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clipy_si_core_ffi_checksum_func_local_seal() != 10304) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clipy_si_core_ffi_checksum_func_make_vault_manifest() != 30149) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clipy_si_core_ffi_checksum_func_manifest_kdf() != 59821) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clipy_si_core_ffi_checksum_func_mask() != 58245) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clipy_si_core_ffi_checksum_func_merge_decide() != 39455) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clipy_si_core_ffi_checksum_func_open_record() != 35330) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clipy_si_core_ffi_checksum_func_record_format_version() != 45962) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clipy_si_core_ffi_checksum_func_rejoin_action() != 50871) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clipy_si_core_ffi_checksum_func_rules_version() != 30659) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clipy_si_core_ffi_checksum_func_seal_record() != 45392) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clipy_si_core_ffi_checksum_func_user_rule_errors() != 51521) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_clipy_si_core_ffi_checksum_func_verify_passphrase() != 53576) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureClipySiCoreFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all